# Generated by Django 5.0.7 on 2024-07-13 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='popularity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
